---
- hosts: all
  become: true
  tasks:
    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Include task to install Consul
      ansible.builtin.include_tasks: includes/install_consul.yml

    - name: Copy consul-server.hcl to /etc/consul.d/consul-server.hcl
      ansible.builtin.copy:
        src: ../files/consul-server.hcl
        dest: /etc/consul.d/consul-server.hcl
        owner: consul
        group: consul
        mode: 0644
      notify: restart consul

  handlers:
    - name: restart consul
      ansible.builtin.systemd:
        name: consul
        state: restarted
        daemon_reload: yes
        enabled: yes