---
- hosts: all
  become: true
  tasks:
    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Include task to install Consul
      ansible.builtin.include_tasks: includes/install_consul.yml

    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Copy haproxy.cfg to /etc/haproxy/haproxy.cfg
      ansible.builtin.copy:
        src: ../files/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: 0600
      notify: restart haproxy

    - name: Copy consul-client.hcl to /etc/consul.d/consul-client.hcl
      ansible.builtin.copy:
        src: ../files/consul-client.hcl
        dest: /etc/consul.d/consul-client.hcl
        owner: consul
        group: consul
        mode: 0644
      notify: restart consul

    - name: Copy haproxy-service.hcl to /etc/consul.d/haproxy-service.hcl
      ansible.builtin.copy:
        src: ../files/haproxy-service.hcl
        dest: /etc/consul.d/haproxy-service.hcl
        owner: consul
        group: consul
        mode: 0644
      notify: restart consul

  handlers:
    - name: restart haproxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted

    - name: restart consul
      ansible.builtin.systemd:
        name: consul
        state: restarted
        daemon_reload: yes
        enabled: yes
