---
- hosts: all
  become: true

  tasks:
    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Include task to install Consul
      ansible.builtin.include_tasks: includes/install_consul.yml

    - name: Include task to install RabbitMQ server
      ansible.builtin.include_tasks: includes/install_rabbitmq_server.yml

    - name: Register Erlang Cookie
      ansible.builtin.command: >-
        cat /var/lib/rabbitmq/.erlang.cookie
      register: erlang_cookie

    - name: Save Erlang Cookie to file
      ansible.builtin.template:
        src: ../templates/erlang_cookie.j2
        dest: /tmp/erlang-cookie
      delegate_to: localhost
      become: no

    - name: Copy consul-client.hcl to /etc/consul.d/consul-client.hcl
      ansible.builtin.copy:
        src: ../files/consul-client.hcl
        dest: /etc/consul.d/consul-client.hcl
        owner: consul
        group: consul
        mode: 0644
      notify: restart consul

    - name: Copy rabbitmq-service.hcl to /etc/consul.d/rabbitmq-service.hcl
      ansible.builtin.copy:
        src: ../files/rabbitmq-service.hcl
        dest: /etc/consul.d/rabbitmq-service.hcl
        owner: consul
        group: consul
        mode: 0644
      notify: restart consul

  handlers:
    - name: restart consul
      ansible.builtin.systemd:
        name: consul
        state: restarted
        daemon_reload: yes
        enabled: yes